export const SAMPLE_DATA = [
  { id: 1, name: 'react' },
  { id: 2, name: 'typescript' },
  { id: 3, name: 'ci/cd' },
  { id: 4, name: 'react-custom-timetable' },
  { id: 5, name: 'dasdsaasda' },
  { id: 6, name: 'dasdsaasda-dasdsaasda-dasdsaasda' },
  { id: 7, name: 'nodejs' },
  { id: 8, name: 'nextjs' },
  { id: 9, name: 'graphql' },
  { id: 10, name: 'jest' },
  { id: 11, name: 'eslint' },
  { id: 12, name: 'prettier' },
  { id: 13, name: 'webpack' },
  { id: 14, name: 'babel' },
  { id: 15, name: 'rollup' },
  { id: 16, name: 'vite' },
  { id: 17, name: 'yarn' },
  { id: 18, name: 'npm' },
  { id: 19, name: 'docker' },
  { id: 20, name: 'kubernetes' },
  { id: 21, name: 'tailwindcss' },
];
