export const SAMPLE_DATA = [
  { id: 1, name: 'react', colorNumber: 1 },
  { id: 2, name: 'typescript', colorNumber: 2 },
  { id: 3, name: 'ci/cd', colorNumber: 3 },
  { id: 4, name: 'react-custom-timetable', colorNumber: 4 },
  { id: 5, name: 'dasdsaasda', colorNumber: 5 },
  { id: 6, name: 'dasdsaasda-dasdsaasda-dasdsaasda', colorNumber: 6 },
  { id: 7, name: 'nodejs', colorNumber: 7 },
  { id: 8, name: 'nextjs', colorNumber: 8 },
  { id: 9, name: 'graphql', colorNumber: 9 },
  { id: 10, name: 'jest', colorNumber: 10 },
  { id: 11, name: 'eslint', colorNumber: 11 },
  { id: 12, name: 'prettier', colorNumber: 12 },
  { id: 13, name: 'webpack', colorNumber: 13 },
  { id: 14, name: 'babel', colorNumber: 14 },
  { id: 15, name: 'rollup', colorNumber: 15 },
  { id: 16, name: 'vite', colorNumber: 16 },
  { id: 17, name: 'yarn', colorNumber: 17 },
  { id: 18, name: 'npm', colorNumber: 18 },
  { id: 19, name: 'docker', colorNumber: 19 },
  { id: 20, name: 'kubernetes', colorNumber: 20 },
  { id: 21, name: 'tailwindcss', colorNumber: 21 },
];
