import { createThemeContract } from '@vanilla-extract/css';

export const commonThemeContract = createThemeContract({
  space: {
    px: '',
    '0.5': '',
    '1': '',
    '1.5': '',
    '2': '',
    '2.5': '',
    '3': '',
    '3.5': '',
    '4': '',
    '5': '',
    '6': '',
    '7': '',
    '8': '',
    '9': '',
    '10': '',
    '12': '',
    '14': '',
    '16': '',
    '20': '',
    '24': '',
    '28': '',
    '32': '',
    '36': '',
    '40': '',
    '44': '',
    '48': '',
    '52': '',
    '56': '',
    '60': '',
    '64': '',
    '72': '',
    '80': '',
    '96': '',
  },
  typography: {
    fontColor: '',
    fontSize: {
      xs: '',
      sm: '',
      md: '',
      lg: '',
      xl: '',
      '2xl': '',
      '3xl': '',
      '4xl': '',
      '5xl': '',
      '6xl': '',
      '7xl': '',
      '8xl': '',
      '9xl': '',
    },
    lineHeight: {
      xs: '',
      sm: '',
      md: '',
      lg: '',
      xl: '',
    },
    fontWeights: {
      hairline: null,
      thin: null,
      light: null,
      normal: null,
      medium: null,
      semibold: null,
      bold: null,
      extrabold: null,
      black: null,
    },
  },
  breakpoints: {
    mobile: '',
    tablet: '',
    desktop: '',
  },
  sizes: {
    max: '',
    min: '',
    full: '',
    '3xs': '',
    '2xs': '',
    xs: '',
    sm: '',
    md: '',
    lg: '',
    xl: '',
    '2xl': '',
    '3xl': '',
    '4xl': '',
    '5xl': '',
    '6xl': '',
    '7xl': '',
    '8xl': '',
    container: {
      sm: '',
      md: '',
      lg: '',
      xl: '',
    },
  },
  borderRadius: {
    none: '',
    sm: '',
    base: '',
    md: '',
    lg: '',
    xl: '',
    '2xl': '',
    '3xl': '',
    full: '',
  },
  zIndex: {
    levelMinus1: null,
    level0: null,
    level1: null,
    level2: null,
    level3: null,
    level4: null,
    level5: null,
    level6: null,
    level7: null,
    level8: null,
    level9: null,
    level10: null,
    level11: null,
  },
});

export const { borderRadius, breakpoints, sizes, space, typography, zIndex } =
  commonThemeContract;
export const { fontColor, fontSize, fontWeights, lineHeight } = typography;
