import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { ToastProvider } from '@/lib/providers/ToastProvider';
import '@/lib/themes/reset.css.ts';
import { ThemeProvider } from '@/lib/providers/ThemeProvider';

const inter = Inter({ subsets: ['latin'] });
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <ToastProvider>
          <ThemeProvider>{children}</ThemeProvider>
        </ToastProvider>
      </body>
    </html>
  );
}
